// @ts-check
const lightwing = require('@lightwing/eslint-config').default

module.exports = lightwing(
  {
    ignores: [
      'dist',
      'node_modules',
      '*.svelte',
      '*.snap',
      '*.d.ts',
      'coverage',
      'js_test',
      'local-data',
    ],
  },
  {
    rules: {
      'node/prefer-global/process': 'off',
      'node/prefer-global/buffer': 'off',
      'no-unused-vars': 'off',
      'no-console': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'unused-imports/no-unused-vars': 'off',
      'semi': 0,
      'antfu/consistent-chaining': 'off',
      'antfu/consistent-list-newline': 'off',
      'antfu/if-newline': 'off',
      'antfu/top-level-function': 'off',
      'format/prettier': 'off',
      'import/consistent-type-specifier-style': 'off',
      'perfectionist/sort-imports': 'off',
      'perfectionist/sort-named-imports': 'off',
      'object-shorthand': 'off',
      'regexp/no-misleading-capturing-group': 'off',
      'regexp/no-super-linear-backtracking': 'off',
      'regexp/no-unused-capturing-group': 'off',
      'regexp/optimal-quantifier-concatenation': 'off',
      'regexp/prefer-w': 'off',
      'regexp/use-ignore-case': 'off',
      'style/arrow-parens': 'off',
      'style/brace-style': 'off',
      'style/comma-dangle': 'off',
      'style/comma-spacing': 'off',
      'style/eol-last': 'off',
      'style/indent': 'off',
      'style/member-delimiter-style': 'off',
      'style/no-multiple-empty-lines': 'off',
      'style/object-curly-spacing': 'off',
      'style/operator-linebreak': 'off',
      'style/padded-blocks': 'off',
      'style/quote-props': 'off',
      'style/quotes': 'off',
      'style/semi': 'off',
      'style/spaced-comment': 'off',
      'test/prefer-lowercase-title': 'off',
      'ts/consistent-type-definitions': 'off',
      'ts/method-signature-style': 'off',
      'ts/no-use-before-define': 'off',
      'unicode-bom': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unused-imports/no-unused-imports': 'off',
      'vue/attributes-order': 'off',
      'vue/block-order': 'off',
      'vue/component-name-in-template-casing': 'off',
      'vue/html-closing-bracket-newline': 'off',
      'vue/html-closing-bracket-spacing': 'off',
      'vue/html-comment-content-spacing': 'off',
      'vue/html-indent': 'off',
      'vue/html-self-closing': 'off',
      'vue/multiline-html-element-content-newline': 'off',
      'vue/no-template-shadow': 'off',
      'vue/no-side-effects-in-computed-properties': 'off',
      'vue/no-useless-v-bind': 'off',
      'vue/padding-line-between-blocks': 'off',
      'vue/singleline-html-element-content-newline': 'off',
      'vue/valid-template-root': 'off',
    },
  },
)
